version: '3.8'

services:
  helloworld:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_DSN: dynamodb:8000
      AWS_REGION: eu-west-2
      SERVICE_PORT: 8080
    depends_on:
      - dynamodb
      - setup-dynamodb

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  setup-dynamodb:
    image: python:3.9-slim
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      TERRAFORM_PATH: /tf/modules/dynamodb/main.tf
      APP_NAME: helloworld
    volumes:
      - ./scripts/initialise_dynamodb_local.py:/tmp/initialise_dynamodb_local.py
      - ./tf:/tf
    entrypoint: [ "sh", "-c", "pip install --upgrade boto3 python-hcl2 && python /tmp/initialise_dynamodb_local.py" ]
    depends_on:
      - dynamodb

volumes:
  dynamodb-data:
