// Code generated by mockery v2.34.0. DO NOT EDIT.

package helloworld

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type StorageMock struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *StorageMock) Save(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageMock {
	mock := &StorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
